version: '3'

services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports: [5432:5432]
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: dev@margeriam.com
            PGADMIN_DEFAULT_PASSWORD: 123
        ports: [5050:80]
#    redis:
#        image: redis:5-alpine
#        ports: [6379]
#    rabbitmq:
#        image: rabbitmq:3.7-management
#        ports: [5672, 15672]
#    mailer:
#        image: schickling/mailcatcher
#        ports: [1025, 1080]
